sudo: false
language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR
before_script:
- npm install get-firefox jpm -g
- cd ..
- get-firefox -p linux -t firefox.tar.bz2
- tar -xjf firefox.tar.bz2 -C firefox
- cd $TRAVIS_BUILD_DIR
script:
- jpm test --tbpl -b $TRAVIS_BUILD_DIR/../firefox/firefox

